# Generated by Django 5.0.7 on 2024-08-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_permissions_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
