# Generated by Django 5.0.7 on 2024-08-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(default=False),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
